title: Can I Mod
url: "http://canimod.com"
repo_url: "https://github.com/canimod/canimod.github.io"
baseurl: ""
cache_version: "r11" # appended to asset paths

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
